services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - legal_check
    depends_on:
      - db

  db:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=legalcheck
    ports:
      - "5432:5432"
    networks:
      - legal_check
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  legal_check:
