services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: lc-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - legal_check
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: lc-test
    volumes:
      - ./:/app
    networks:
      - legal_check
    depends_on:
      - db
      - api



  db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: lc-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=legalcheck
    ports:
      - "5432:5432"
    networks:
      - legal_check
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  legal_check:
