"""add invite code to company

Revision ID: 47e7ac331c56
Revises: e6f5c9d9447a
Create Date: 2025-04-14 15:49:34.872879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e7ac331c56'
down_revision: Union[str, None] = 'e6f5c9d9447a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('invite_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'invite_code')
    # ### end Alembic commands ###
