"""add soft deletes to models

Revision ID: de8d98c06f64
Revises: 47e7ac331c56
Create Date: 2025-04-16 13:37:20.642883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8d98c06f64'
down_revision: Union[str, None] = '47e7ac331c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_analysis_results_is_deleted'), 'analysis_results', ['is_deleted'], unique=False)
    op.add_column('checklists', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_checklists_is_deleted'), 'checklists', ['is_deleted'], unique=False)
    op.add_column('companies', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.add_column('conversations', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_conversations_is_deleted'), 'conversations', ['is_deleted'], unique=False)
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    op.add_column('embeddings', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_embeddings_is_deleted'), 'embeddings', ['is_deleted'], unique=False)
    op.add_column('linked_documents', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_linked_documents_is_deleted'), 'linked_documents', ['is_deleted'], unique=False)
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_messages_is_deleted'), 'messages', ['is_deleted'], unique=False)
    op.add_column('policies', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_policies_is_deleted'), 'policies', ['is_deleted'], unique=False)
    op.add_column('policy_rules', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_policy_rules_is_deleted'), 'policy_rules', ['is_deleted'], unique=False)
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_column('user', 'is_deleted')
    op.drop_index(op.f('ix_policy_rules_is_deleted'), table_name='policy_rules')
    op.drop_column('policy_rules', 'is_deleted')
    op.drop_index(op.f('ix_policies_is_deleted'), table_name='policies')
    op.drop_column('policies', 'is_deleted')
    op.drop_index(op.f('ix_messages_is_deleted'), table_name='messages')
    op.drop_column('messages', 'is_deleted')
    op.drop_index(op.f('ix_linked_documents_is_deleted'), table_name='linked_documents')
    op.drop_column('linked_documents', 'is_deleted')
    op.drop_index(op.f('ix_embeddings_is_deleted'), table_name='embeddings')
    op.drop_column('embeddings', 'is_deleted')
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.drop_column('documents', 'is_deleted')
    op.drop_index(op.f('ix_conversations_is_deleted'), table_name='conversations')
    op.drop_column('conversations', 'is_deleted')
    op.drop_index(op.f('ix_companies_is_deleted'), table_name='companies')
    op.drop_column('companies', 'is_deleted')
    op.drop_index(op.f('ix_checklists_is_deleted'), table_name='checklists')
    op.drop_column('checklists', 'is_deleted')
    op.drop_index(op.f('ix_analysis_results_is_deleted'), table_name='analysis_results')
    op.drop_column('analysis_results', 'is_deleted')
    # ### end Alembic commands ###
